service: pdf-studio-api

frameworkVersion: '3'

# Provider configuration
provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  
  # Global environment variables
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    SERVICE_NAME: ${self:service}
    
    # DynamoDB
    DYNAMODB_TABLE: ${self:service}-main-${self:provider.stage}
    
    # S3
    S3_BUCKET: ${self:service}-files-${self:provider.stage}-${self:provider.region}
    
    # AWS Cognito
    COGNITO_USER_POOL_ID: !Ref UserPool
    COGNITO_USER_POOL_CLIENT_ID: !Ref UserPoolClient
    
  # Global function defaults
  timeout: 25
  memorySize: 256
  
  # Tracing and monitoring
  tracing:
    lambda: true
    apiGateway: true
    
  # Logs retention
  logs:
    httpApi: true
    
  # HTTP API CORS configuration
  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:5173  # Vite dev server
        - https://pdf-studio.vercel.app
      allowedHeaders:
        - Content-Type
        - Authorization
        - X-Requested-With
        - Accept
        - Origin
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowCredentials: true
    
  # IAM permissions - imported from separate file
  iam:
    role:
      statements: ${file(infrastructure/iam/lambda-execution-role.yml):iamRoleStatements}

# Plugins
plugins:
  - serverless-esbuild

# Package configuration
package:
  patterns:
    - '!node_modules/**'

# Custom configuration
custom:
  # Disable Serverless Framework Observability instrumentation
  serverlessFrameworkObservability:
    enabled: false
  
  # ESBuild configuration for TypeScript compilation
  esbuild:
    bundle: true
    minify: false  # Keep readable for debugging
    sourcemap: false  # Disable sourcemaps for smaller bundles
    exclude: 
      - 'aws-sdk'
      - 'mock-aws-s3' 
      - 'nock'
    target: 'node20'
    define:
      'require.resolve': undefined
      'process.env.NODE_ENV': '"production"'
    external: 
      - 'aws-sdk'
      - 'mock-aws-s3'
      - 'nock'
    loader:
      '.html': 'text'
    platform: 'node'
    concurrency: 10
    keepNames: true
    treeShaking: false
    format: 'cjs'
    mainFields: ['main', 'module']
    conditions: ['node']

# Functions configuration
functions: ${file(infrastructure/functions.yml)}

# Import resources from separate files
resources:
  # DynamoDB resources
  - ${file(infrastructure/resources/dynamodb.yml)}
  
  # S3 resources
  - ${file(infrastructure/resources/s3.yml)}
  
  # AWS Cognito resources
  - ${file(infrastructure/resources/cognito.yml)}
