Resources:
  # PostgreSQL RDS Instance (publicly accessible for simplicity)
  PostgreSQLInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      DBInstanceIdentifier: ${self:service}-postgres-${self:provider.stage}
      DBName: ${self:custom.database.name}
      Engine: postgres
      EngineVersion: '15.7'
      
      # Instance configuration
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      MaxAllocatedStorage: 100
      StorageType: gp2
      StorageEncrypted: true
      
      # Credentials
      MasterUsername: ${self:custom.database.username}
      MasterUserPassword: ${self:custom.database.password}
      
      # Network configuration (publicly accessible for development)
      PubliclyAccessible: true
      
      # Backup configuration
      BackupRetentionPeriod: 7
      PreferredBackupWindow: "03:00-04:00"
      PreferredMaintenanceWindow: "sun:04:00-sun:05:00"
      
      # Multi-AZ disabled for cost savings
      MultiAZ: false
      
      # Deletion protection disabled for development
      DeletionProtection: false
      
      Tags:
        - Key: Name
          Value: ${self:service}-postgres-${self:provider.stage}
        - Key: Stage
          Value: ${self:provider.stage}
        - Key: Service
          Value: ${self:service}

Outputs:
  PostgreSQLEndpoint:
    Description: PostgreSQL RDS instance endpoint
    Value: !GetAtt PostgreSQLInstance.Endpoint.Address
    Export:
      Name: ${self:service}-postgres-endpoint-${self:provider.stage}

  PostgreSQLPort:
    Description: PostgreSQL RDS instance port
    Value: !GetAtt PostgreSQLInstance.Endpoint.Port
    Export:
      Name: ${self:service}-postgres-port-${self:provider.stage}

  DatabaseName:
    Description: PostgreSQL database name
    Value: ${self:custom.database.name}
    Export:
      Name: ${self:service}-db-name-${self:provider.stage}