# Authentication Functions
functions:
  login:
    handler: src/functions/auth/login.main
    description: "User login endpoint"
    events:
      - httpApi:
          path: /auth/login
          method: post
    environment:
      FUNCTION_NAME: login
    
  register:
    handler: src/functions/auth/register.main
    description: "User registration endpoint"
    events:
      - httpApi:
          path: /auth/register
          method: post
    environment:
      FUNCTION_NAME: register