# File Management Functions
functions:
  generateUploadUrl:
    handler: src/functions/files/generate-url.main
    description: "Generate presigned URL for file upload"
    timeout: 30
    memorySize: 256
    events:
      - httpApi:
          path: /files/upload-url
          method: post
    environment:
      FUNCTION_NAME: generateUploadUrl
      
  confirmUpload:
    handler: src/functions/files/confirm.main
    description: "Confirm file upload completion"
    timeout: 30
    memorySize: 256
    events:
      - httpApi:
          path: /files/confirm-upload
          method: post
    environment:
      FUNCTION_NAME: confirmUpload
      
  listFiles:
    handler: src/functions/files/list.main
    description: "List user's uploaded files"
    timeout: 30
    memorySize: 256
    events:
      - httpApi:
          path: /files
          method: get
    environment:
      FUNCTION_NAME: listFiles
      
  getFile:
    handler: src/functions/files/get.main
    description: "Get a file by ID or generate download URL"
    events:
      - httpApi:
          path: /files/{fileId}
          method: get
    environment:
      FUNCTION_NAME: getFile
      
  deleteFile:
    handler: src/functions/files/delete.main
    description: "Delete a file from S3"
    events:
      - httpApi:
          path: /files/{fileId}
          method: delete
    environment:
      FUNCTION_NAME: deleteFile