# Health check
health:
  handler: src/functions/health/handler.main
  description: 'Health check endpoint'
  timeout: 10
  memorySize: 128
  events:
    - httpApi:
        path: /health
        method: get

# Authentication Functions - All removed, using Pure Cognito
# No backend auth endpoints needed with pure Cognito authentication

# Template Functions
createTemplate:
  handler: src/functions/templates/create.main
  description: 'Create a new template from uploaded file'
  timeout: 30
  memorySize: 512
  events:
    - httpApi:
        path: /templates
        method: post
  environment:
    MAIN_TABLE: ${self:provider.environment.DYNAMODB_TABLE}

getTemplate:
  handler: src/functions/templates/get-by-id.main
  description: 'Get template by ID'
  timeout: 15
  memorySize: 256
  events:
    - httpApi:
        path: /templates/{templateId}
        method: get
  environment:
    MAIN_TABLE: ${self:provider.environment.DYNAMODB_TABLE}

listTemplates:
  handler: src/functions/templates/get.main
  description: 'List all templates'
  timeout: 15
  memorySize: 256
  events:
    - httpApi:
        path: /templates
        method: get
  environment:
    MAIN_TABLE: ${self:provider.environment.DYNAMODB_TABLE}

updateTemplate:
  handler: src/functions/templates/update.main
  description: 'Update template'
  timeout: 25
  memorySize: 512
  events:
    - httpApi:
        path: /templates/{templateId}
        method: put
  environment:
    MAIN_TABLE: ${self:provider.environment.DYNAMODB_TABLE}

deleteTemplate:
  handler: src/functions/templates/delete.main
  description: 'Delete template'
  timeout: 15
  memorySize: 256
  events:
    - httpApi:
        path: /templates/{templateId}
        method: delete
  environment:
    MAIN_TABLE: ${self:provider.environment.DYNAMODB_TABLE}

createBlankTemplate:
  handler: src/functions/templates/create-blank.main
  description: 'Create a blank template'
  timeout: 15
  memorySize: 256
  events:
    - httpApi:
        path: /templates/blank
        method: post
  environment:
    MAIN_TABLE: ${self:provider.environment.DYNAMODB_TABLE}

# Field Functions
createField:
  handler: src/functions/fields/create.main
  description: 'Create a new field'
  timeout: 15
  memorySize: 256
  events:
    - httpApi:
        path: /fields
        method: post
  environment:
    MAIN_TABLE: ${self:provider.environment.DYNAMODB_TABLE}

getTemplateFields:
  handler: src/functions/fields/get.main
  description: 'Get fields for a template'
  timeout: 15
  memorySize: 256
  events:
    - httpApi:
        path: /templates/{templateId}/fields
        method: get
  environment:
    MAIN_TABLE: ${self:provider.environment.DYNAMODB_TABLE}

getField:
  handler: src/functions/fields/get-by-id.main
  description: 'Get field by ID'
  timeout: 15
  memorySize: 256
  events:
    - httpApi:
        path: /fields/{fieldId}
        method: get
  environment:
    MAIN_TABLE: ${self:provider.environment.DYNAMODB_TABLE}

updateField:
  handler: src/functions/fields/update.main
  description: 'Update field'
  timeout: 15
  memorySize: 256
  events:
    - httpApi:
        path: /fields/{fieldId}
        method: put
  environment:
    MAIN_TABLE: ${self:provider.environment.DYNAMODB_TABLE}

deleteField:
  handler: src/functions/fields/delete.main
  description: 'Delete field'
  timeout: 15
  memorySize: 256
  events:
    - httpApi:
        path: /fields/{fieldId}
        method: delete
  environment:
    MAIN_TABLE: ${self:provider.environment.DYNAMODB_TABLE}

# File Functions
listFiles:
  handler: src/functions/files/get.main
  description: 'List uploaded files'
  timeout: 15
  memorySize: 256
  events:
    - httpApi:
        path: /files
        method: get
  environment:
    MAIN_TABLE: ${self:provider.environment.DYNAMODB_TABLE}
    S3_BUCKET: ${self:provider.environment.S3_BUCKET}

uploadFile:
  handler: src/functions/files/upload.main
  description: 'Upload file to S3'
  timeout: 30
  memorySize: 512
  events:
    - httpApi:
        path: /files/upload
        method: post
  environment:
    MAIN_TABLE: ${self:provider.environment.DYNAMODB_TABLE}
    S3_BUCKET: ${self:provider.environment.S3_BUCKET}

# PDF Functions
generatePDF:
  handler: src/functions/pdf/generate.main
  description: 'Generate PDF from template'
  timeout: 60
  memorySize: 1024
  events:
    - httpApi:
        path: /pdf/generate
        method: post
  environment:
    MAIN_TABLE: ${self:provider.environment.DYNAMODB_TABLE}
    S3_BUCKET: ${self:provider.environment.S3_BUCKET}
