# Lambda execution role with necessary permissions
iamRoleStatements:
  # DynamoDB permissions for single table design
  - Effect: Allow
    Action:
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
      - dynamodb:BatchGetItem
      - dynamodb:BatchWriteItem
    Resource:
      - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
      - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}/index/*"
  
  # S3 permissions for file storage
  - Effect: Allow
    Action:
      - s3:GetObject
      - s3:PutObject
      - s3:DeleteObject
      - s3:GetObjectVersion
      - s3:PutObjectAcl
    Resource:
      - "arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*"
  
  - Effect: Allow
    Action:
      - s3:ListBucket
      - s3:GetBucketLocation
      - s3:GetBucketVersioning
    Resource:
      - "arn:aws:s3:::${self:provider.environment.S3_BUCKET}"

  # CloudWatch Logs permissions
  - Effect: Allow
    Action:
      - logs:CreateLogGroup
      - logs:CreateLogStream
      - logs:PutLogEvents
      - logs:DescribeLogGroups
      - logs:DescribeLogStreams
    Resource:
      - "arn:aws:logs:${self:provider.region}:*:log-group:/aws/lambda/*"
  
  # CloudWatch Metrics permissions
  - Effect: Allow
    Action:
      - cloudwatch:PutMetricData
      - cloudwatch:GetMetricStatistics
      - cloudwatch:ListMetrics
    Resource: "*"
  
  # X-Ray permissions for tracing
  - Effect: Allow
    Action:
      - xray:PutTraceSegments
      - xray:PutTelemetryRecords
    Resource: "*"
  
  # AWS Cognito permissions
  - Effect: Allow
    Action:
      - cognito-idp:AdminCreateUser
      - cognito-idp:AdminSetUserPassword
      - cognito-idp:AdminDeleteUser
      - cognito-idp:AdminGetUser
      - cognito-idp:AdminInitiateAuth
      - cognito-idp:AdminRespondToAuthChallenge
      - cognito-idp:AdminConfirmSignUp
      - cognito-idp:GetUser
      - cognito-idp:UpdateUserAttributes
      - cognito-idp:AdminUpdateUserAttributes
      - cognito-idp:ListUsers
      - cognito-idp:ForgotPassword
      - cognito-idp:ConfirmForgotPassword
      - cognito-idp:ResendConfirmationCode
    Resource:
      - "arn:aws:cognito-idp:${self:provider.region}:*:userpool/*"
  
